# Generated by Django 5.2 on 2025-05-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_blogpost_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("contact", models.CharField(max_length=15)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("message", models.TextField()),
            ],
        ),
    ]
