# Generated by Django 5.2 on 2025-05-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="subTitle",
            field=models.CharField(default="", max_length=300),
        ),
    ]
