# Generated by Django 5.2 on 2025-05-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_service_subtitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.ImageField(default="default_image.jpg", upload_to=""),
        ),
    ]
