# Generated by Django 5.2 on 2025-05-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_service_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactus",
            name="footer_text",
            field=models.TextField(default=""),
        ),
    ]
