# Generated by Django 5.2 on 2025-05-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_contactus_footer_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("info", models.TextField()),
            ],
        ),
    ]
