# Generated by Django 5.2.4 on 2025-07-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_homerequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clients", models.IntegerField(default=0)),
                ("projects", models.IntegerField(default=0)),
                ("awards", models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="service",
            name="icons",
            field=models.ImageField(default="icons.jpg", upload_to=""),
        ),
        migrations.AlterField(
            model_name="sociallink",
            name="title",
            field=models.CharField(
                choices=[
                    ("FB", "FACEBOOK"),
                    ("IG", "INSTAGRAM"),
                    ("X", "X(TWITTER"),
                    ("YT", "YOUTUBE"),
                ],
                max_length=10,
            ),
        ),
    ]
