# Generated by Django 5.2.4 on 2025-07-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_sociallink_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sociallink",
            name="title",
            field=models.CharField(
                choices=[
                    ("FB", "FACEBOOK"),
                    ("IG", "INSTAGRAM"),
                    ("X", "X(TWITTER)"),
                    ("YT", "YOUTUBE"),
                    ("LN", "LINKEDIN"),
                ],
                max_length=10,
            ),
        ),
    ]
