# Generated by Django 5.2.4 on 2025-07-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_sociallink_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sociallink",
            name="link",
        ),
        migrations.RemoveField(
            model_name="sociallink",
            name="title",
        ),
        migrations.AddField(
            model_name="sociallink",
            name="facebook",
            field=models.URLField(default=""),
        ),
        migrations.AddField(
            model_name="sociallink",
            name="instagram",
            field=models.URLField(default=""),
        ),
        migrations.AddField(
            model_name="sociallink",
            name="linkedin",
            field=models.URLField(default=""),
        ),
        migrations.AddField(
            model_name="sociallink",
            name="x",
            field=models.URLField(default=""),
        ),
        migrations.AddField(
            model_name="sociallink",
            name="youtube",
            field=models.URLField(default=""),
        ),
    ]
