# Generated by Django 5.2.4 on 2025-07-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_remove_sociallink_link_remove_sociallink_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chooseus",
            name="icon",
            field=models.ImageField(default="", upload_to=""),
        ),
    ]
