# Generated by Django 5.2.4 on 2025-07-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_chooseus_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="mission",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="about",
            name="values",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="about",
            name="vision",
            field=models.TextField(default=""),
        ),
    ]
